### ISSUE TITLE
询问一下LIKE语句应该如何查询

### ISSUE THREAD

**Issue by cheneyweb** [PeterMu/nodebatis#2]
你好，nodebatis真的是非常好的持久层封装，但是目前遇到了LIKE语句的查询问题，想询问一下yml中应该如何编写LIKE语句，能否给出一个示例呢，十分感谢：）

**Comment by PeterMu** [comment]
使用方法和 `=` 是一样的，在调用时，根据实际情况给传递的参数前面或后面加上 `%`

### test.yml
```
namespace: 'test'
likeDemo: select * from test where id like :id
```

### 调用
`nodebatis.query('test.likeDemo', { id: '%123%' })`
