### ISSUE TITLE
支持forEach的mybatis动态sql规则吗？现在好像只有if 的介绍

### ISSUE THREAD

**Issue by Newsqueak** [PeterMu/nodebatis#4]

**Comment by PeterMu** [comment]
@Newsqueak 
最近抽空更新了一版，已经支持 for 的形式。
```
for:
    array: array,
    sql: statements
    seperator: ','
```
* `array`, 要遍历的数组，数组内的数据必须是对象。
* `sql`, 每次遍历要填充的 sql，使用 :key 的形式引用 array 中的对象的数据。
* `seperator`, 每次遍历填充的 sql 之间的分隔符。
