### ISSUE TITLE
会支持MySQL以外的数据库吗？

### ISSUE THREAD

**Issue by FurryWolfX** [PeterMu/nodebatis#5]
会支持MySQL以外的数据库吗？

**Comment by oscWolfX** [comment]
阅读源码的时候发现很多transaction误拼成了transation... 😂

**Comment by PeterMu** [comment]
有计划支持，最早设计的时候已经考虑了兼容多种数据库，因为时间的关系没有实现。您这边想我兼容哪个数据库？

wolfx <notifications@github.com>于2018年11月5日 周一11:55写道：

**Comment by PeterMu** [comment]
囧了，我查了下还真是，我抽空抓紧改了。

wolfx <notifications@github.com>于2018年11月5日 周一12:52写道：

**Comment by oscWolfX** [comment]
> 有计划支持，最早设计的时候已经考虑了兼容多种数据库，因为时间的关系没有实现。您这边想我兼容哪个数据库？ wolfx <notifications@github.com>于2018年11月5日 周一11:55写道：
SQLserver 和 Oracle 这种常用的最好支持下，虽然我们这里用的最多的也是 MySQL，不过还是会有例外的。
