### ISSUE TITLE
关于条件查询

### ISSUE THREAD

**Issue by Hugh1029** [PeterMu/nodebatis#7]
关于条件查询if的使用，如果if条件均不存在，那么sql语句就会报错，需要在通过where 1=1的方式来规避if条件不存在的情况

**Comment by PeterMu** [comment]
fixed by @Hugh1029 on commit [2480feaff4f39939ae68ad3460333e15f031e06a](https://github.com/PeterMu/nodebatis/commit/2480feaff4f39939ae68ad3460333e15f031e06a)
